api:
  base_url: "https://api.studio.nebius.com/v1/"
  timeout: 30
  max_retries: 3

models:
  embedding: "BAAI/bge-en-icl"
  llm: "meta-llama/Meta-Llama-3.1-8B-Instruct"

processing:
  batch_size: 50
  max_text_length: 2000
  sample_size: 150
  
outlier_detection:
  euclidean_radius: 0.55
  contamination_rate: 0.05
  lof_neighbors: 20
  confidence_level: 0.99

visualization:
  umap_neighbors: 15
  umap_min_dist: 0.1
  random_state: 42

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"