apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-outlier-detection
  labels:
    app: ai-outlier-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-outlier-detection
  template:
    metadata:
      labels:
        app: ai-outlier-detection
    spec:
      containers:
      - name: api
        image: ai-outlier-detection:latest
        ports:
        - containerPort: 8000
        env:
        - name: NEBIUS_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: nebius-api-key
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-outlier-detection-service
spec:
  selector:
    app: ai-outlier-detection
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer